version: "3.2"
services:
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ddos_simulator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private
    logging:
      options:
        max-size: "1m"
  redis:
    container_name: redis
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - private
    logging:
      options:
        max-size: "1m"
  api:
    container_name: api
    image: api
    build: api
    restart: always
    env_file:
      - ./api/.env
    volumes:
      - api_static:/opt/app/static
    networks:
      - public
      - private
    logging:
      options:
        max-size: "1m"
    depends_on:
      - postgres
      - redis
  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - api_static:/opt/app/static
    networks:
      - public
    logging:
      options:
        max-size: "1m"
    depends_on:
      - api
volumes:
  postgres_data:
  redis_data:
  api_static:
networks:
  public:
  private:
